# Server Configuration
server:
  port: 99
  error:
    include-message: always

spring:
  web:
    resources:
      add-mappings: true

---

# Spring Configuration
spring:
  datasource:
    name: ds_mariadb
    username: root
    password: 2204
    url: jdbc:mariadb://localhost:3306/nDB
    driver-class-name: org.mariadb.jdbc.Driver

  # Hibernate Configuration
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

# this 3 dash is use to seperate the spring block
---
# Spring Configuration
spring:
  datasource:
    name: ds_postgres
    driver-class-name: org.postgresql.Driver
    username: numan
    password: 2204
    hikari:
      schema: sch_springBoot
    url: jdbc:postgresql://localhost:5432/nDB


  # Hibernate Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
# ddl-auto: create-drop means tables with create & drop soon app stop running
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true

